### ISSUE TITLE
Add a Github Actions workflow dispatch

### ISSUE THREAD

**Issue by allenkinzalow** [osrs-wiki/osrs-wiki-maps#3]
Add a Github Actions workflow dispatch to run the map export tool. The action should download both the cache in idx format and xteas and run `MapExport` and `stitch.py`.

**Comment by samszotkowski** [comment]
Is the idea to have the Action create a zip file and add it to latest release then have some script on the map server pick up that file each week and do whatever needs to happen server-side?  Are there size limitations or can we go nuts publishing a ~500MB file each week?
